name: build
on: [pull_request, push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Configure Gradle Cache
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.gradle/caches
                      ./gradle/loom-cache
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
            - name: Validate Gradle Wrapper
              uses: gradle/actions/wrapper-validation@v4
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'zulu'
            - name: Ensure Gradle Wrapper is executable
              run: chmod +x ./gradlew
            - name: Build
              run: ./gradlew build
            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: Artifacts
                  path: ./**/build/libs/
